@startuml 
user -> Search: queryText
Search -> SparseModel: list(embed(queryText)) 
Search -> DenseModel: list(embed(queryText))
Search -> QdrantClient: query_batch_points
Search <-- QdrantClient: search_results
Search -> point: payload

@enduml