@startuml 
Dataset -> Dataset: loadDataset(), select(), filter() 
Dataset -> DataFrame: to_pandas()
DataFrame -> DataFrame: drop_duplicates(), dropna()
DataFrame -> DataFrame: df[combined_fields]
DataFrame -> DenseModel: TextEmbedding
DenseModel -> DenseModel: download model
DataFrame -> DenseModel: list(embed(product_texts)
DenseModel --> DataFrame: df[dense_embedding]
DataFrame -> SparseModel: sparseTextEmbedding
SparseModel -> SparseModel: download model
DataFrame -> SparseModel: list(embed(product_texts) 
SparseModel --> DataFrame: df[sparse_embedding]
QdrantClient -> QdrantClient: create collection
DataFrame -> QdrantClient: df[dense_embedding], df[sparse_embedding], df[product_texts]
QdrantClient -> PointStruct: vector(dense_vector, sparse_vector), payload(product)
PointStruct --> QdrantClient: points
QdrantClient -> QdrantClient: upsert(collection_name, points)
@enduml